# code: language=ansible
---

- name: Check ring installation
  when: license_ring is undefined
  block:

    - name: Find ring binnary
      ansible.builtin.find:
        paths: /opt/1C/1CE/components
        patterns: "ring"
        recurse: true
      register: _results_path

    - name: Gather ring info
      when: _results_path.files[0].path is defined
      block:

        - name: Get ring versions
          ansible.builtin.command: "{{ _results_path.files[0].path }} --version"
          changed_when: false
          register: _results_version

        - name: Get ring modules
          ansible.builtin.command: "{{ _results_path.files[0].path }} help modules"
          changed_when: false
          register: _results_modules

        - name: Set ring info
          ansible.builtin.set_fact:
            license_ring: "{{ {'path': _results_path.files[0].path, 'version': _results_version.stdout, 'modules': _results_modules.stdout} }}"
